In [0]:
import pandas as pd
import numpy as np
from IPython.display import display

In [0]:
df = pd.read_json('airlines-1558527599826.json', orient = 'records', lines = True)

In [0]:
df.columns

Index(['contributors', 'coordinates', 'created_at', 'delete',
       'display_text_range', 'entities', 'extended_entities', 'extended_tweet',
       'favorite_count', 'favorited', 'filter_level', 'geo', 'id', 'id_str',
       'in_reply_to_screen_name', 'in_reply_to_status_id',
       'in_reply_to_status_id_str', 'in_reply_to_user_id',
       'in_reply_to_user_id_str', 'is_quote_status', 'lang', 'place',
       'possibly_sensitive', 'quote_count', 'quoted_status',
       'quoted_status_id', 'quoted_status_id_str', 'quoted_status_permalink',
       'reply_count', 'retweet_count', 'retweeted', 'retweeted_status',
       'source', 'text', 'timestamp_ms', 'truncated', 'user'],
      dtype='object')

In [0]:
df[['id','in_reply_to_screen_name','in_reply_to_status_id','in_reply_to_status_id_str','in_reply_to_user_id','in_reply_to_user_id_str']].head(10)

,id,in_reply_to_screen_name,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str
0,1.131173e+18,None,NaN,NaN,NaN,NaN
1,1.131173e+18,None,NaN,NaN,NaN,NaN
2,1.131173e+18,AlexanderViol,1.131033e+18,1.131033e+18,3.943766e+08,3.943766e+08
3,1.131173e+18,None,NaN,NaN,NaN,NaN
4,1.131173e+18,None,NaN,NaN,NaN,NaN
5,1.131173e+18,None,NaN,NaN,NaN,NaN
6,1.131173e+18,None,NaN,NaN,NaN,NaN
7,1.131173e+18,easyJet,1.131101e+18,1.131101e+18,3.867690e+07,3.867690e+07
8,1.131173e+18,None,NaN,NaN,NaN,NaN
9,1.131173e+18,BilalEksiTHY,NaN,NaN,7.888827e+17,7.888827e+17

In [0]:
df['conversation']=df['in_reply_to_status_id'].copy()

In [0]:
df.loc[np.isnan(df['conversation']),'conversation']=df[np.isnan(df['conversation'])]['id']

In [0]:
len(df['conversation'].value_counts())

12213

In [0]:
import math
import datetime

[Timedelta('-1 days +23:57:18.248000'), Timedelta('-1 days +23:55:55.491000'), Timedelta('-1 days +23:59:45.412000')]

Timedelta('-1 days +23:57:39.717000')

In [1]:
time_tweet = df['timestamp_ms'].tolist()
conversat = df['conversation'].tolist()
textlist = df['text'].tolist()


def ResponseTime(mention):
    indexes = []
    convers = []
    conversuniq = []
    conversdup = []
    convtime = []
    response_time = []
    for i in range(len(textlist)):
        if mention in str(textlist[i]):
            indexes.append(i)                           #indexes of tweets mentioning the mention
    for i in range(len(indexes)):
        convers.append(df['conversation'][i])           #conversation numbers of tweets involving the mention
    for val in convers:
        if val in conversuniq:
            conversdup.append(val)
        if val not in conversuniq:
            conversuniq.append(val)                     #list of actual conversations ID's with mention 
    for i in range(len(conversdup)):                    #loop over list of conversations with response.
        index_conv = indexes[i]                         #index in whole dataframe of conversation
        request = time_tweet[index_conv]                #time of mention
        for i in range(len(conversat)):                 #check for conversation value and gather tweets which are equal
            if conversat[i] == conversat[index_conv]:
                convtime.append(time_tweet[i])
        sorted(convtime)
        for i in range(len(convtime)-1):
            if convtime[i] is request:
                response_time.append(convtime[i+1]-convtime[i])
    average_timedelta = sum(response_time, datetime.timedelta(0)) / len(response_time)
    return("The average time it takes for {} to respond to a tweet is {}".format(mention, average_timedelta))
  

ResponseTime("@AmericanAir")

NameError: ignored